POST http://localhost:8080/school/student
Accept: application/json
Content-Type: application/json

{
  "firstname" : "Michal",
  "lastname" : "Novak",
  "email" : "michal@novak",
  "grade" : "BC"
}

###

POST http://localhost:8080/school/student
Accept: application/json
Content-Type: application/json

{
  "id" : "1",
  "firstname" : "Michal",
  "lastname" : "Novak",
  "email" : "michal@novak",
  "grade" : "BC"
}

###

POST http://localhost:8080/school/student
Accept: application/json
Content-Type: application/json

{
  "id" : "2",
  "firstname" : "Michal",
  "lastname" : "Novak",
  "email" : "michal@novak",
  "grade" : "BC"
}
