POST http://localhost:8080/school/student
Accept: application/json
Content-Type: application/json

{
  "firstname" : "Michal",
  "lastname" : "Novak",
  "email" : "michal@novak",
  "grade" : "BC"
}

###

POST http://localhost:8080/school/student
Accept: application/json
Content-Type: application/json

{
  "firstname" : "Filip",
  "lastname" : "Novak",
  "email" : "filip@novak",
  "grade" : "BC"
}

###

GET http://localhost:8080/school/student
Accept: application/json

###